### ISSUE TITLE
Data validation

### ISSUE THREAD

**Issue by ns-rse** [CUREd-Plus/cuRed#7]
Data validation using the [validate package](https://cran.r-project.org/web/packages/validate/vignettes/cookbook.html) should be implemented. Rules can be written in [YAML](https://yaml.org).

For example `age` should always be a positive integer bounded by an upper limit (e.g. `120`)

```yaml
rules:
- expr: age >= 0
  name: 'age'
  label: 'age positivity'
  description: |
    age can not be negative
  created: 2023-07-11 11:15:11
  meta:
    language: validate 0.9.3.36
    severity: error
```
